version: "1.0"
services:
  haipproxy:
    build: .
    command: sh run.sh
    volumes:
      - .:/haipproxy
    ports:
      - "8000:8000"
      - "3128:3128"
    links:
      - redis
      - splash

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
#    command: >
#      --requirepass 123456

  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"

